// Code generated by goctl. DO NOT EDIT!
// Source: counter.proto

package server

import (
	"context"

	"web_game/service/counter/rpc/counter"
	"web_game/service/counter/rpc/internal/logic"
	"web_game/service/counter/rpc/internal/svc"
)

type CounterServer struct {
	svcCtx *svc.ServiceContext
	counter.UnimplementedCounterServer
}

func NewCounterServer(svcCtx *svc.ServiceContext) *CounterServer {
	return &CounterServer{
		svcCtx: svcCtx,
	}
}

func (s *CounterServer) Query(ctx context.Context, in *counter.ReqQuery) (*counter.ResQuery, error) {
	l := logic.NewQueryLogic(ctx, s.svcCtx)
	return l.Query(in)
}

func (s *CounterServer) Update(ctx context.Context, in *counter.ReqUpdate) (*counter.ResUpdate, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}
