// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"web_game/service/user/rpc/internal/logic"
	"web_game/service/user/rpc/internal/svc"
	"web_game/service/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.ReqLogin) (*user.ResLogin, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Binding(ctx context.Context, in *user.ReqBinding) (*user.ResBinding, error) {
	l := logic.NewBindingLogic(ctx, s.svcCtx)
	return l.Binding(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.ReqUserInfo) (*user.ResUserInfo, error) {
	l := logic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
