// Code generated by goctl. DO NOT EDIT!
// Source: trace.proto

package server

import (
	"context"

	"web_game/service/trace/rpc/internal/logic"
	"web_game/service/trace/rpc/internal/svc"
	"web_game/service/trace/rpc/trace"
)

type TraceServer struct {
	svcCtx *svc.ServiceContext
	trace.UnimplementedTraceServer
}

func NewTraceServer(svcCtx *svc.ServiceContext) *TraceServer {
	return &TraceServer{
		svcCtx: svcCtx,
	}
}

func (s *TraceServer) PushTrace(ctx context.Context, in *trace.ReqTrace) (*trace.ResTrace, error) {
	l := logic.NewPushTraceLogic(ctx, s.svcCtx)
	return l.PushTrace(in)
}
