// Code generated by goctl. DO NOT EDIT.
package types

type ReqLogin struct {
	AppVersion string `json:"app_version"` //客户端版本号
	Account    string `json:"account"`     //账号
	AccToken   string `json:"acc_token"`   //登录凭据
	LoginType  int32  `json:"login_type"`  //登录方式
	Time       int32  `json:"time"`        //时间
	DeviceId   string `json:"device_id"`   //设备id，用于校验请求次数频率等
	Invitation int32  `json:"invitation"`  //邀请码
	Channel    string `json:"channel"`     //渠道码
}

type ResLogin struct {
	ErrNo        int32  `json:"err_no"`        //错误码，0=成功，其他数字代表各种失败
	ErrMsg       string `json:"err_msg"`       //错误信息
	Jwt          string `json:"jwt"`           //jwt token, 用于下次登录的凭据
	GuestAccount string `json:"guest_account"` //如果是游客登录，把游客随机账号返回给客户端
	IsReg        bool   `json:"is_reg"`        //是否是首次注册
}

type ResUserInfo struct {
	PlayerId     int32  `json:"player_id"`
	Name         string `json:"name"`
	Gender       int32  `json:"gender"`
	AvatorUrl    string `json:"avator_url"`
	InvitationId int32  `json:"invitation_id"`
	Channel      string `json:"channel"`
	VipLv        int32  `json:"vip_lv"`
	VipExp       int64  `json:"vip_exp"`
	Level        int32  `json:"level"`
	LevelExp     int64  `json:"level_exp"`
}

type ReqBinding struct {
	OpenId      string `json:"open_id"`
	AccessToken string `json:"access_token"`
}

type ResBindding struct {
	ErrNo  int32  `json:"err_no"`  //错误码，0=成功，其他数字代表各种失败
	ErrMsg string `json:"err_msg"` //错误信息
}
